### ISSUE TITLE
Return result containing references

### ISSUE THREAD

**Issue by SetheenDev** [rmanoka/async-scoped#11]
Hello!  I'd like to use this library but cannot figure out how to return references.  This is the equivalent using raw crossbeam:
```rust
fn main(){
    let group1 = [1,2,3];
    let group2 = [4,5,6];
    let groups = [group1, group2];
    let results = crossbeam::scope(|s| {
        let mut results = Vec::<&i32>::new();
        let mut handles = vec![];
        for group in &groups {
            handles.push(s.spawn(move |_| {
                &group[0]
            }));
        }
        for handle in handles {
            results.push(handle.join().unwrap());
        }
        results
    });
    
    println!("{:?}", results.unwrap());
}
```
[playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=14a3c9334892e22751ad2028b54b2a1a)

Using the async version, _"&groups does not live long enough"_:
```rust
let group1 = [1,2,3];
let group2 = [4,5,6];
let groups = [group1, group2];
let results = async_scoped::TokioScope::scope_and_block(|s| {
    for group in &groups {
        s.spawn(async {
            &group[0]
        });
    }
});
```
Same with _scope_and_collect_.  I don't think this is a bug, I'm new to rust and could use a pointer if this is possible.  Thanks!

**Comment by rmanoka** [comment]
Nice catch @SetheenDev !  crossbeam uses some sync. mechanisms to store the returned objects, that our design does not do.  This causes a restriction on the output of the future being `'static`.  We could try to implement the crossbeam-style mechanism too, but I don't know how big a change it is / how it might affect performance.

For now, you could use sync. mechanisms like `oneshot` or `mpsc` channels of the tokio or futures crates.  It is a bit more verbose, but should get around the lifetime issues.

**Comment by SetheenDev** [comment]
Thanks for responding @rmanoka.  I didn't think about oneshot but that seems perfect!  Thank you!
