### ISSUE TITLE
Release async-scoped 0.9 version

### ISSUE THREAD

**Issue by akoshelev** [rmanoka/async-scoped#27]
This issue can be closed once 0.9 version is published to `crates.io`

**Comment by rmanoka** [comment]
Been a bit swamped at work; apologies.  I wanted to try to fix the doc bug before releasing it.

@akoshelev Do you have bandwidth to publish this, and handle issues and PRs on this repo?  I should also chime in when I find some time.

**Comment by akoshelev** [comment]
sure I can step in and help. Let me know what is the process to publish it to crates.io (I believe I need to have access to the registry key)

**Comment by rmanoka** [comment]
Yeah, what's your crates.io username?  I'll add you as an owner in the crate.

**Comment by akoshelev** [comment]
I am using github authentication, so it should be the same as my github username

**Comment by rmanoka** [comment]
Great, I've sent an invite.

**Comment by rmanoka** [comment]
I see 0.9.0 is release on crates.io.   Closing this.

**Comment by rmanoka** [comment]
Thanks @akoshelev !
