### ISSUE TITLE
scope_and_collect should return results in order of submission

### ISSUE THREAD

**Issue by stepancheg** [rmanoka/async-scoped#29]
`scope_and_collect` function uses `FuturesUnordered` under the hood, so it returns futures in no order.

Unordered makes sense when we handle stream, but in `collect` operation it makes little sense and add complexity on caller side.

(Also `scope_and_collect` does not document that it returns results unordered).

**Comment by rmanoka** [comment]
This has been fixed in master, and should be released soon.

**Comment by rmanoka** [comment]
Done in 0.9.0
