### ISSUE TITLE
tokio?

### ISSUE THREAD

**Issue by stevemk14ebr** [rmanoka/async-scoped#3]
Are there plans for official support for tokio? I am curious what the technical blockers to this may be.

**Comment by stevemk14ebr** [comment]
is this the equivalent? https://tokio-rs.github.io/tokio/doc/tokio/task/fn.block_in_place.html

**Comment by rmanoka** [comment]
Nice find!  The function takes a `FnOnce` and blocks on it, but what we currently need is a function that takes a `Future`.   I think we should be able to use this functionality for instance, by running a single-thread executor of the `Future` we wish to drive within the `FnOnce` passed to `block_in_place`.  However, we have to evaluate this a bit more carefully, and ensure complete safety.

Unfortunately, I can't provide a timeline for doing this yet.  I could guide you on this, if you are interested in providing a PR.

**Comment by rmanoka** [comment]
@stevemk14ebr I tried a tokio implementation in this PR: https://github.com/rmanoka/async-scoped/pull/4 .   See [tests](https://github.com/rmanoka/async-scoped/blob/feat/tokio/src/tests.rs#L251) for example usage.

tokio's `block_in_place` is such a great functionality;  interestingly it prevents a particular deadlock that happens with deep recursive usage of `Scope`.  However, it can only be called from an async context, so slightly different from similar functionality of async_std.

**Comment by stevemk14ebr** [comment]
Thanks for taking the time to work on that!
